{% set name = "pymultinest" %}
{% set version = "2.7" %}
{% set sha256 = "fd7386b546582a51433d93e8bfd6d75fbe558199501f0568ce7e9a1cca0fa7c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
   number: 2
   skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - pytest-runner
    - setuptools
  run:
    - python
    - matplotlib
    - multinest
    - numpy >=1.11,<2.0a0
    - scipy

test:
  imports:
    - pymultinest
  commands:
    - python ${PREFIX}/share/pymultinest/pymultinest_demo_minimal.py


about:
  home: http://johannesbuchner.github.com/PyMultiNest/
  dev_url: https://github.com/JohannesBuchner/PyMultiNest
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Access module for the MultiNest'

extra:
  recipe-maintainers:
    - giacomov
    - JohannesBuchner
    - beckermr
