{% set name = "pymultinest" %}
{% set version = "2.9" %}
{% set sha256 = "f8a85ccc89c02c679c967f883b14cb75b1c23a627838dd950868eaf324a48edb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
   number: 1
   skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - pytest-runner
    - setuptools
  run:
    - python
    - matplotlib-base
    - multinest
    - numpy >=1.11,<2.0a0
    - scipy

test:
  imports:
    - pymultinest

about:
  home: http://johannesbuchner.github.com/PyMultiNest/
  dev_url: https://github.com/JohannesBuchner/PyMultiNest
  license: GPL3
  license_family: GPL
  license_file: LICENSE
  summary: 'Bayesian computations with the nested sampling algorithm MultiNest.'

extra:
  recipe-maintainers:
    - giacomov
    - JohannesBuchner
    - beckermr
