{% set name = "pymultinest" %}
{% set version = "2.7" %}
{% set sha256 = "fd7386b546582a51433d93e8bfd6d75fbe558199501f0568ce7e9a1cca0fa7c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
   number: 1
   skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - multinest
    - numpy >=1.11
    - scipy
    - matplotlib
    - pytest
    - pytest-runner

  run:
    - python
    - multinest
    - scipy
    - matplotlib
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pymultinest
  commands:
    - python ${CONDA_PREFIX}/share/pymultinest/pymultinest_demo_minimal.py


about:
  home: http://johannesbuchner.github.com/PyMultiNest/
  license: GPL-3
  summary: 'Access module for the MultiNest'
  license_family: GPL
  dev_url: https://github.com/JohannesBuchner/PyMultiNest
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

extra:
  recipe-maintainers:
    - giacomov
    - JohannesBuchner
    - beckermr
