{% set name = "pymultinest" %}
{% set version = "2.11" %}
{% set sha256 = "b853d3757875419827a1fd361c054f33db24b7360c1ef5db6dc90d2ee51e07ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - pytest-runner
    - setuptools
  run:
    - python
    - matplotlib-base
    - multinest
    - numpy >=1.11,<2.0a0
    - scipy

test:
  imports:
    - pymultinest

about:
  home: http://johannesbuchner.github.com/PyMultiNest/
  dev_url: https://github.com/JohannesBuchner/PyMultiNest
  license: GPL3
  license_family: GPL
  license_file: LICENSE
  summary: Bayesian computations with the nested sampling algorithm MultiNest.

extra:
  recipe-maintainers:
    - giacomov
    - JohannesBuchner
